# Generated by Django 3.1.5 on 2021-01-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commented_on_account',
            name='commented_on_account_username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='promo_account',
            name='promo_username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='promo_account',
            name='target_account',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='brand_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
