# Generated by Django 3.1.5 on 2021-01-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210112_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo_account',
            name='comment_rounds_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promo_account',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
