# Generated by Django 3.1.5 on 2021-01-17 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210117_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commented_on_account',
            old_name='username',
            new_name='commented_on_account_username',
        ),
    ]
