# Generated by Django 3.1.5 on 2021-01-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210117_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo_account',
            name='comment_rounds_today',
            field=models.IntegerField(default=0),
        ),
    ]
