# Generated by Django 3.1.5 on 2021-02-07 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210206_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='commented_on_account',
            name='promo_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.promo_account'),
        ),
        migrations.AddField(
            model_name='promo_account',
            name='comments_until_sleep',
            field=models.IntegerField(default=800),
        ),
    ]
