# Generated by Django 3.1.5 on 2021-01-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210115_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo_account',
            name='comment_rounds_today',
        ),
    ]
