# Generated by Django 3.1.5 on 2021-01-16 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_promo_account_comment_rounds_today'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo_account',
            old_name='password',
            new_name='promo_password',
        ),
        migrations.RenameField(
            model_name='promo_account',
            old_name='username',
            new_name='promo_username',
        ),
        migrations.AlterField(
            model_name='promo_account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Commented_On_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
