# Generated by Django 3.1.5 on 2021-01-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_promo_account_comment_rounds_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo_account',
            name='to_run_at',
        ),
        migrations.AddField(
            model_name='promo_account',
            name='is_queued',
            field=models.BooleanField(default=False),
        ),
    ]
