# Generated by Django 3.1.5 on 2021-01-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210116_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promo_account',
            name='promo_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='promo_account',
            name='promo_username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='promo_account',
            name='proxy',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='promo_account',
            name='target_account',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=15, unique=True),
        ),
    ]
