# Generated by Django 3.1.5 on 2021-02-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_promo_account_is_liking'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo_account',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
