# Generated by Django 3.1.5 on 2021-02-27 20:47

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_promo_account_is_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_min_followers', models.IntegerField(default=0)),
                ('account_max_followers', models.IntegerField(default=50000)),
                ('account_min_number_following', models.IntegerField(default=0)),
                ('account_max_number_following', models.IntegerField(default=5000)),
                ('account_description_avoided_key_phrases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('post_min_number_of_comments', models.IntegerField(default=0)),
                ('post_max_number_of_comments', models.IntegerField(default=500)),
                ('post_min_number_of_likes', models.IntegerField(default=0)),
                ('post_max_number_of_likes', models.IntegerField(default=10000)),
                ('post_description_avoided_key_phrases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
