# Generated by Django 3.1.5 on 2021-03-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210305_0236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetPasswordToken',
            new_name='EmailValidationToken',
        ),
        migrations.AddField(
            model_name='user',
            name='validated_email',
            field=models.BooleanField(default=False),
        ),
    ]
