# Generated by Django 3.1.5 on 2021-03-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210306_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo_account',
            name='is_resting',
            field=models.BooleanField(default=False),
        ),
    ]
