# Generated by Django 3.1.5 on 2021-03-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_promo_account_using_comment_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo_account',
            name='failed_last_comment_round',
            field=models.BooleanField(default=False),
        ),
    ]
